Skoda.DIAS.UI/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using Skoda.DIAS.Common;
using Skoda.DIAS.Common.Helpers;
using Skoda.DIAS.Data.Models;
using Skoda.DIAS.Models;
using Skoda.DIAS.Services;
using Skoda.DIAS.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using System.IO;
using Skoda.DIAS.Common.Enums;
using System.Text;
using Microsoft.Extensions.Primitives;

namespace Skoda.DIAS.UI.Controllers
{
    [Authorize]
    [SessionExpireAttribute]
    public class DashboardController : BaseController
    {
        public readonly ILogger<DelearController> _logger;
        public SMTPSettings _smtpSettings;
        private IHostingEnvironment _environment;
        public DashboardController(IWebHostEnvironment hostingEnvironment, ILogger<DelearController> logger, IConfiguration config, SkodaContext skodaContext, IOptions<SMTPSettings> smtpSettings, IHostingEnvironment environment)
            : base(hostingEnvironment, config, skodaContext)
        {
            _logger = logger;
            _smtpSettings = smtpSettings.Value;
            _environment = environment;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> Download(string file)
        {
            string FilePath = Path.Combine(_environment.WebRootPath, "uploads") + "/" + GetEnquiryId() + "/" + file;
            var memory = new MemoryStream();
            using (var stream = new FileStream(FilePath, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, GetContentType(FilePath), Path.GetFileName(FilePath));
        }
        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> MasterDownload(string file)
        {
            string FilePath = Path.Combine(_environment.WebRootPath, "uploads") + "/documents/" + file;
            var memory = new MemoryStream();
            using (var stream = new FileStream(FilePath, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, GetContentType(FilePath), Path.GetFileName(FilePath));
        }
        private string GetContentType(string path)
        {
            var types = GetMimeTypes();
            var ext = Path.GetExtension(path).ToLowerInvariant();
            return types[ext];
        }
        private Dictionary<string, string> GetMimeTypes()
        {
            return new Dictionary<string, string>
            {
        {".txt", "text/plain"},
        {".pdf", "application/pdf"},
        {".ppt", "application/x-mspowerpoint"},
        {".pptx", "application/x-mspowerpoint"},
        {".pps", "application/x-mspowerpoint"},
        {".doc", "application/vnd.ms-word"},
        {".docx", "application/vnd.ms-word"},
        {".xls", "application/vnd.ms-excel"},
        {".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
        {".png", "image/png"},
        {".jpg", "image/jpeg"},
        {".jpeg", "image/jpeg"},
        {".gif", "image/gif"},
        {".csv", "text/csv"}
            };
        }
        private string GetEnquiryId()
        {
            DealerModel dInfo = null;
            if (HttpContext.Session.TryGetValue("DelearLoginWithOtp", out byte[] delearBytes))
            {
                dInfo = ObjectToByte.ByteArrayToObject<DealerModel>(delearBytes);
            }
            return dInfo.Enquiry_id;
        }
        [AllowAnonymous]
        [HttpGet]
        public IActionResult List()
        {
            Enquiry uInfo = null;

            if (HttpContext.Session.TryGetValue("DelearLogin", out byte[] user))
            {
                uInfo = ObjectToByte.ByteArrayToObject<Enquiry>(user);
            }
            List<DealerList> model = new List<DealerList>();
            model = (from c in _skodaContext.Delear_Enquiry
                     where c.Mobile_No == uInfo.Mobile
                     select new DealerList()
                     {
                         Brand = c.Brand_name,
                         BusinessName = c.Brand_name,
                         City = _skodaContext.City.Where(x => x.Id == c.City_Id).Select(x => x.Name).FirstOrDefault(),
                         EnquiryId = c.Enquiry_id,
                         BusinessType = c.Bussiness_Type,
                         FullName = c.Fullname,
                         Pincode = c.Pincode,
                         CreatedDt = c.Created_Date.ToString("dd MM yyyy")
                     }).ToList();
            return View(model);
        }
        [AllowAnonymous]
        public IActionResult Index(string id)
        {

            var singlerecord = _skodaContext.Delear_Enquiry.Where(x => x.Enquiry_id == id).Select(c => new { c.Status_ID, c.Enquiry_id, c.Created_Date, c.Mobile_No, c.Email, c.Bussiness_Type, c.City_Id, c.Fullname, c.Dealer_ID, c.State_Id }).FirstOrDefault();
            ViewBag.DealerName = singlerecord.Fullname;
            ViewBag.BussinessRegistered = singlerecord.Created_Date;

            DealerModel model = new DealerModel();
            model.Fullname = singlerecord.Fullname;
            model.Enquiry_id = singlerecord.Enquiry_id;
            model.Mobile_No = singlerecord.Mobile_No;
            model.Dealer_ID = singlerecord.Dealer_ID;
            model.Email = singlerecord.Email;
            model.City = _skodaContext.City.Where(x => x.Id == singlerecord.City_Id).Select(y => y.Name).FirstOrDefault();
            model.Bussiness_Type = singlerecord.Bussiness_Type;
            HttpContext.Session.Set("DelearLoginWithOtp", ObjectToByte.ObjectToByteArray(model));

            var StatusId = singlerecord.Status_ID;
            if (StatusId == 1)
            {
                ViewBag.Status = "Open";
            }
            else if (StatusId == 2)
            {
                ViewBag.Status = "OnHold";
            }
            else if (StatusId == 3)
            {
                ViewBag.Status = "Rejected";
            }
            else if (StatusId == 4)
            {
                ViewBag.Status = "Approved";
            }
            var stages = _skodaContext.Enquiry_Status.Where(x => x.Enquiry_Id == singlerecord.Enquiry_id).Select(c => new { c.Stage_id, c.Enquiry_Id, c.Created_Date, c.ModifyDate }).FirstOrDefault();
            if (stages != null)
            {
                ViewBag.DocumentSubmitted = stages.Created_Date;
                ViewBag.modifyDate = stages.ModifyDate;
                var msg = "";
                if (stages.Stage_id > 0)
                {
                    var Name = _skodaContext.Stages.Where(x => x.Id == stages.Stage_id).Select(c => new { c.Description }).FirstOrDefault();
                    ViewBag.StageName = Name.Description;

                    ViewBag.Stage = stages.Stage_id;
                }
                else
                {
                    msg = "Enquiry ID does not exist!";
                    return Json(msg);
                }
            }
            List<DealerActivity> activity = new List<DealerActivity>();
            var tmp = _skodaContext.DealerActivity.Where(x => x.Delear_ID == singlerecord.Dealer_ID).OrderByDescending(x => x.Created_date).ToList();
            foreach (var line in tmp)
            {
                if (line.Description != "")
                {
                    var Isadmin = line.Description.Split(" ")[0];
                    if (Isadmin != "Admin")
                    {
                        activity.Add(new DealerActivity { Id = line.Id, Description = line.Description, Delear_ID = line.Delear_ID, Comment = line.Comment, Created_date = line.Created_date });
                    }
                }
                //Console.WriteLine(line);
            }
            ViewBag.activities = activity;
            ViewBag.attachDocuments = _skodaContext.UploadDocument.Where(x => x.Delear_ID == singlerecord.Dealer_ID).OrderByDescending(x => x.Created_date).ToList();
            ViewBag.MasterDocuments = _skodaContext.Admin_FileUpload.OrderByDescending(x => x.CreatedDate).ToList();
            ViewBag.Count = _skodaContext.Delear_Enquiry.Where(x => x.Mobile_No == singlerecord.Mobile_No).Count();
            var Zoneid = _skodaContext.State.Where(x => x.Id == singlerecord.State_Id).FirstOrDefault();
            if (Zoneid != null)
            {
                var ZoneData = _skodaContext.Zone.Where(x => x.Id == Zoneid.ZoneId).FirstOrDefault();
                var ZoneDatas = _skodaContext.Support_Email.Where(x => x.Id == Zoneid.ZoneId).FirstOrDefault();
                Location student2 = new Location
                {
                    ZoneName = ZoneData.Name,
                    FullName = ZoneDatas.FullName,
                    Email = ZoneDatas.Email
                };
                ViewBag.Support = student2;
            }
            return View();
        }
        public class SomeQuery
        {
            public string Para { get; set; }
        }
        public class Location
        {
            public string ZoneName { get; set; }
            public string FullName { get; set; }
            public string Email { get; set; }
        }
        [AllowAnonymous]
        [HttpPost]
        public IActionResult FileUpload()
        {
            var filelist = HttpContext.Request.Form.Files;

            DealerModel dInfo = null;
            if (HttpContext.Session.TryGetValue("DelearLoginWithOtp", out byte[] delearBytes))
            {

Skoda.DIAS.UI/Views/Shared/_DealerInLayout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    string username = ViewBag.UserName;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"]</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />

    <!-- Bootstrap core CSS -->
    <link href="~/fonts/fonts.css" rel="stylesheet" />
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/vendor/select2/select2.min.css" rel="stylesheet" />
    <link href="~/vendor/custom_scrollbar/jquery.mCustomScrollbar.min.css" rel="stylesheet" />
    <link href="~/css/dealer/dealer-style.css" rel="stylesheet" />
    <link href="~/vendor/dataTables/jquery.dataTables.css" rel="stylesheet" />
    <link href="~/vendor/custom_scrollbar/jquery.mCustomScrollbar.min.css" rel="stylesheet" />
    <link href="~/vendor/toggleMenu/vmenuModule.css" rel="stylesheet" />   
    <link href="~/vendor/fontAwesome/css/font-awesome.css" rel="stylesheet" />
    @RenderSection("Styles", required: false)
    <script src="~/vendor/jquery/jquery.js"></script>
</head>
<body>
    <div class="dealer-header">
        <header>
            <div class="logo-wrp">
                <img src="~/images/login/SkodaLogo.svg" class="img-fluid" alt="skoda logo" />
            </div>
            <div class="user-service">
                <a class="dropdown-toggle"
                   href="#"
                   id="navbardropdownUserLink"
                   role="button"
                   data-toggle="dropdown"
                   aria-haspopup="true"
                   aria-expanded="false">
                    <img src="~/images/icons/user.svg" class="rounded-circle" width="20px" height="20px" />
                </a>
                <div class="dropdown-menu" aria-labelledby="navbardropdownUserLink">
                    <a class="dropdown-item" href="#">@username </a>
                    <a class="dropdown-item" href="#">Dashboard</a>
                    @*<a class="dropdown-item" href="@Url.Action(" Profile", "Dashboard" )">Edit Profile</a>*@
                    <a class="dropdown-item" href="@Url.Action("Logout", "Delear" )">Log Out</a>
                </div>
            </div>
        </header>
        <div class="breadcrumb">
            Go to <span class="breadcrumb-item"><a href="../Delear/Signup">Homepage</a></span>
        </div>
    </div>
    <div class="container">
        <div class="banner">
            <a href="/Delear/Signup">  <img src="~/images/login/banner-y.png" class="img-fluid" alt="banner" /></a>
        </div>
        <div class="delear-card-wrapper">
            @RenderBody()
        </div>

    </div>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script> 
        var baseUrl = "@Url.Content("~/")";
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Skoda.DIAS.UI/Views/Shared/_DealerLayout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    string username = ViewBag.UserName;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"]</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />


    <!-- Bootstrap core CSS -->
    <link href="~/fonts/fonts.css" rel="stylesheet" />
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/vendor/select2/select2.min.css" rel="stylesheet" />
    <link href="~/vendor/custom_scrollbar/jquery.mCustomScrollbar.min.css" rel="stylesheet" />
    <link href="~/css/dealer/dealer-style.css" rel="stylesheet" />
    <link href="~/vendor/dataTables/jquery.dataTables.css" rel="stylesheet" /> 
    <link href="~/vendor/fontAwesome/css/font-awesome.css" rel="stylesheet" />
    @RenderSection("Styles", required: false)
    <script src="~/vendor/jquery/jquery.js"></script>
</head>
<body>
    <div class="dealer-header">
        <header>
            <div class="logo-wrp">
                <img src="~/images/login/SkodaLogo.svg" class="img-fluid" alt="skoda logo" />
            </div>
        </header>
        <div class="breadcrumb">
            Go to <span class="breadcrumb-item"><a href="../Delear/Signup">Homepage</a></span>
        </div>
    </div>
    <div class="container">
        <div class="banner">
            <img src="~/images/login/banner-y.png" class="img-fluid" alt="banner" />
        </div>
        <div class="delear-card-wrapper">
            @RenderBody()
        </div>

    </div>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/select2/select2.full.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script>
        var baseUrl = "@Url.Content("~/")";
    </script>

    @RenderSection("Scripts", required: false)

    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
            $('select').select2({
                allowClear: true
            });

            $('input').focus(function () {
                $(this).parents('.custom-field').addClass('focused');
            });
            

            $('input').blur(function () {
                var inputValue = $(this).val();
                if (inputValue == "") {
                    $(this).removeClass('filled');
                    $(this).parents('.custom-field').removeClass('focused');
                } else {
                    $(this).addClass('filled');
                }
            })


        })
    </script>
</body>
</html>

Skoda.DIAS.UI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    string username = ViewBag.UserName;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"]</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />
    <!-- Bootstrap core CSS -->
    <link href="~/fonts/fonts.css" rel="stylesheet" />
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/vendor/select2/select2.min.css" rel="stylesheet" />
    <link href="~/vendor/custom_scrollbar/jquery.mCustomScrollbar.min.css" rel="stylesheet" />
    <link href="~/vendor/toggleMenu/vmenuModule.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link media="screen" rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" />
    @RenderSection("Styles", required: false)
    <script src="~/vendor/jquery/jquery.js"></script>
    <script src="~/vendor/custom_scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
</head>
<body>
    <header>
        <div class="header-left">
            @*<div class="burger-icon">
                <img class="img-fluid" src="~/images/icons/burger-icon.svg" alt="menu icon" />
            </div>*@
            <div class="header-logo">
                <img class="img-fluid" src="~/images/login/SkodaLogo.svg" alt="logo" />
            </div>
        </div>
        <div class="header-right">
            <div class="notif-wrp">
                <a class="dropdown-toggle"
                   id="notificationdropdownUserLink"
                   role="button"
                   data-toggle="dropdown"
                   aria-expanded="false">
                    <div class="notif_count">
                        <span class="noti-value" id="NotificationCount"></span>
                        <img class="img-fluid"
                             src="~/images/icons/notification-icon.svg"
                             alt="notification" />
                    </div>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown" id="NotificationContainer">
                    <h4 class="class=" dropdown-item"">Notifications</h4>
                    <div class="noti-list-wrp">

                    </div>

                </div>
            </div>
            <div class="user-service">
                <a class="dropdown-toggle"
                   href="#"
                   id="navbardropdownUserLink"
                   role="button"
                   data-toggle="dropdown"
                   aria-haspopup="true"
                   aria-expanded="false">
                    <img src="~/images/icons/user.svg" class="rounded-circle" />
                </a>
                <div class="dropdown-menu" aria-labelledby="navbardropdownUserLink">

                    <a class="dropdown-item" href="#">@username </a>
                    <a class="dropdown-item" href="@Url.Action("Profile", "Admin")">Edit Profile</a>
                    <a class="dropdown-item" href="@Url.Action("Logout", "Admin")">Log Out</a>
                </div>
            </div>
        </div>
    </header>
    <div class="dashboard-wrapper">
        <main>
            @RenderBody()
        </main>
    </div>
    @RenderSection("RenderFooter", required: false)

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script> 
    <script src="~/vendor/stickybits/stickybits.min.js"></script>
    <script src="~/vendor/select2/select2.full.js"></script>
    <script src="~/vendor/toggleMenu/vmenuModule.js"></script>
    <script type="text/jscript">
        $(document).ready(function () {
            var inputfield = document.getElementsByClassName("form__field");

            for (i = 0; i < inputfield.length; i++) {

                var inputValue = $(inputfield[i]).val();
                $(inputfield[i]).parents('.custom-field').addClass('focused');
                if (inputValue == "") {
                    $(inputfield[i]).removeClass('filled');
                    $(inputfield[i]).parents('.custom-field').removeClass('focused');
                } else {
                    $(inputfield[i]).addClass('filled');
                }
            }

            $('input').focus(function () {
                $(this).parents('.custom-field').addClass('focused');
            });

            $('input').blur(function () {
                var inputValue = $(this).val();
                if (inputValue == "") {
                    $(this).removeClass('filled');
                    $(this).parents('.custom-field').removeClass('focused');
                } else {
                    $(this).addClass('filled');
                }
            })

            $('textarea').focus(function () {
                $(this).parents('.custom-field').addClass('focused');
            });


            $('textarea').blur(function () {
                var inputValue = $(this).val();
                if (inputValue == "") {
                    $(this).removeClass('filled');
                    $(this).parents('.custom-field').removeClass('focused');
                } else {
                    $(this).addClass('filled');
                }
            })

            stickybits("header"); 

            $('select').select2({
                dropdownPosition: 'below'
            });
            $(function GetNotifications() {

                $.ajax({
                    type: 'POST',
                    url: baseUrl + 'Admin/FetchNotification',
                    async: false,
                    cache: false,
                    success: function (response) {
                        if (response.result == "success") {
                            $("#NotificationCount").html(response.data.length);
                        }
                        for (i = 0; i < response.data.length; i++) {
                          
                            var a = "<a class='dropdown-item' href='../Admin/InvokeNotification?id=" + response.data[i].id + "&delearId=" + response.data[i].delearId + "'>" + response.data[i].message + "</a>";
                          //  var anchor = $("<a class='dropdown-item' href='"+ baseUrl + "Admin/InvokeNotification?id=" + response.data[i].id + "&delearId=" + response.data[i].delearId + "'>" + response.data[i].message + "</a>");
                            $('#NotificationContainer .noti-list-wrp').append(a);
                        }


                    },
                    complete: function () {
                        $("#NotificationContainer .noti-list-wrp").mCustomScrollbar();
                    },
                    error: function () {
                    }
                });
            })
        });
         var baseUrl = "@Url.Content("~/")";
    </script> 
    @RenderSection("Scripts", required: true)
</body>
</html>

Skoda.DIAS.UI/Views/Shared/_LeftMenu.cshtml
@model string
@{
    string role = ViewBag.Role;
}
<aside class="sidebar u-vmenu">
    <ul class="list-unstyled">
        @if (@role == "Admin")
        {
            <li><a href="@Url.Action("DelearEnquiry", "Admin")" class="@(Model.Equals("ManageEnquiry", StringComparison.InvariantCulture) ? "active" : "") nav-icon nav-icon-dash"> <span>Enquiry List</span> </a></li>
            <li><a href="@Url.Action("Index", "Admin")" class="@(Model.Equals("ManageUsers", StringComparison.InvariantCulture) ? "active" : "") nav-icon nav-icon-user"> <span>Manage Users</span> </a></li>
            <li><a href="@Url.Action("RoleList", "Admin")" class="@(Model.Equals("ManageRole", StringComparison.InvariantCulture) ? "active" : "") nav-icon nav-icon-roles"> <span>Roles</span> </a></li>
            <li><a href="@Url.Action("ZoneList", "Admin")" class="@(Model.Equals("ManageZone", StringComparison.InvariantCulture) ? "active" : "") nav-icon nav-icon-zones"> <span>Zones</span> </a></li>
            <li><a href="@Url.Action("StateList", "Admin")" class="@(Model.Equals("ManageState", StringComparison.InvariantCulture) ? "active" : "") nav-icon nav-icon-city"> <span>States</span> </a></li>
            <li><a href="@Url.Action("CityList", "Admin")" class="@(Model.Equals("ManageCity", StringComparison.InvariantCulture) ? "active" : "") nav-icon nav-icon-city"> <span>Cities</span> </a></li>
            <li><a href="@Url.Action("DocumentIndex", "Admin")" class="@(Model.Equals("ManageDocs", StringComparison.InvariantCulture) ? "active" : "") nav-icon nav-icon-doc"><span>Documents</span></a></li>
            <li>
                <a href="@Url.Action("Profile", "Admin")" class="@(Model.Equals("Admin", StringComparison.InvariantCulture) ? "active" : "") nav-icon nav-icon-user "> <span>Profiles</span> </a>
            </li>

        }
        else
        {
            <li><a href="@Url.Action("DelearEnquiry", "Admin")" class="@(Model.Equals("ManageEnquiry", StringComparison.InvariantCulture) ? "active" : "") nav-icon nav-icon-dash"> <span>Enquiry List</span> </a></li>
            <li><a href="@Url.Action("DocumentIndex", "Admin")" class="@(Model.Equals("ManageDocs", StringComparison.InvariantCulture) ? "active" : "") nav-icon nav-icon-doc"><span>Documents</span></a></li>
            <li>
                <a href="@Url.Action("Profile", "Admin")" class="@(Model.Equals("Admin", StringComparison.InvariantCulture) ? "active" : "") nav-icon nav-icon-user "> <span>Profiles</span> </a>
            </li>
        }
    </ul>
</aside>

Skoda.DIAS.UI/Views/Shared/_LoginLayout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{

}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"]</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />

    <!-- Bootstrap core CSS -->
    <link href="~/fonts/fonts.css" rel="stylesheet" />
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/vendor/select2/select2.min.css" rel="stylesheet" />
    <link href="~/vendor/custom_scrollbar/jquery.mCustomScrollbar.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/css/dealer/dealer-style.css" rel="stylesheet" />
    @RenderSection("Styles", required: false)
    <script src="~/vendor/jquery/jquery.js"></script>
    <style>
        body {
            background: #F3F4F4;
        }
    </style>
</head>
<body>
    <div class="dealer-header">
        <header>
            <div class="container">
                <div class="logo-wrp">
                    <img src="~/images/login/SkodaLogo.svg" class="img-fluid" alt="skoda logo" />
                </div>
            </div>
        </header>
    </div>
    @RenderBody()
    @RenderSection("RenderFooter", required: false)
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/custom_scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/vendor/stickybits/stickybits.min.js"></script>
    <script src="~/vendor/select2/select2.full.js"></script>
    <script>
        var baseUrl = "@Url.Content("~/")";



    </script>
    @RenderSection("Scripts", required: false)


</body>
</html>