Skoda.DIAS.UI/Controllers/ChangePasswordController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Skoda.DIAS.Common;
using Skoda.DIAS.Data.Models;
using Skoda.DIAS.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Skoda.DIAS.UI.Controllers
{
    [Authorize]
    [SessionExpire]
    public class ChangePasswordController : BaseController
    {
       
        public ChangePasswordController(IWebHostEnvironment hostingEnvironment, ILogger<AdminController> logger, IConfiguration config, SkodaContext skodaContext, IOptions<SMTPSettings> smtpSettings)
            : base(hostingEnvironment, config, skodaContext)
        {
        }


        public IActionResult Index(int id)
        {
            var changePasswordModel = new ChangePasswordModel() {
                UserId = id,
                OldPassword = "",
                NewPassword = "",
                ConfirmPassword = ""
            };
            return View(changePasswordModel);
        }

        [HttpPost]
        public IActionResult Index(ChangePasswordModel model) {

            if (model != null && model.OldPassword != null && model.OldPassword != "" &&
                model.NewPassword != null && model.NewPassword != "" &&
                model.ConfirmPassword != null && model.ConfirmPassword != "")
            {
                var encPassword = EncryptDecryptUtils.Encrypt(PhraseKey, Convert.ToString(model.OldPassword));
                var exuser = _skodaContext.Users.Where(u => u.UserId == model.UserId && u.Password == encPassword).FirstOrDefault();
                if (exuser != null)
                {
                    if (model.NewPassword == model.ConfirmPassword)
                    {
                        var encNewPassword = EncryptDecryptUtils.Encrypt(PhraseKey, Convert.ToString(model.NewPassword));
                        exuser.Password = encNewPassword;
                        _skodaContext.Users.Update(exuser);
                        _skodaContext.SaveChanges();
                        return RedirectToAction("Profile", "Admin");
                    }
                    else {
                        ViewBag.Message = "New Password and Confirm Password didn't match";
                    }
                }
                else {
                    ViewBag.Message = "Please enter correct existing password";
                }
            }
            else {
                ViewBag.Message = "All fields are mandatory";
            }

            return View();
        }
    }
}

Skoda.DIAS.UI/Views/Admin/ActivityList.cshtml
@model List<ActivityDetails>
@{
    ViewData["Title"] = "ŠKODA India > Acitity";
    Layout = "_Layout";
}

@section Styles {
    <link href="~/vendor/dataTables/jquery.dataTables.css" rel="stylesheet" />
}
@{ await Html.RenderPartialAsync("_LeftMenu", "ManagerUsers"); }
<div class="dashboard">
    <div class="dashboard-inner">
        <table id="activity" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>
                        Description
                    </th>
                    <th>
                        Comment
                    </th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                @if (@Model != null)
                {
                    @foreach (var m in @Model)
                    {
                        <tr>
                            <td>@m.Description</td>
                            <td>@m.Comment</td>
                            <td>@m.Created_date</td>
                        </tr>

                    }
                }
            </tbody>
        </table>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

Skoda.DIAS.UI/Views/Admin/CityList.cshtml
@model List<CityDetails>
@{
    ViewData["Title"] = "ŠKODA India > City";
}
 
@section Styles {
    <link href="~/vendor/dataTables/jquery.dataTables.css" rel="stylesheet" />
}
@{ await Html.RenderPartialAsync("_LeftMenu", "ManageCity"); }
<div class="dashboard">
    <div class="dashboard-inner"> 
        <a class="btn btn-primary mb-3" asp-action="CityCreate">Create New</a>
        <table id="city" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
            <thead>
                <tr> 
                    <th>
                        Zone
                    </th>
                    <th>
                        City
                    </th> 
                    <th>PinCode</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @if (@Model != null)
                {
                    @foreach (var m in @Model)
                    {
                <tr>
                    <td>@m.ZoneName</td>
                    <td>@m.Name</td>
                    <td><a class="pincode-wrp">@m.Pincode</a></td>
                    <td><a class="btn-edit" href="@Url.Action("CityCreate", "Admin")?id= @m.Id"></a></td>
                    <td><a href='#' class='btn-delete' onclick="DeleteData(@m.Id); return false;"></a></td>
                </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>
 
@section Scripts
{

    <script src="~/vendor/dataTables/jquery.dataTables.min.js"></script>

    <script type="text/javascript">
        $(function () {
            

            $.ajax({
                type: "POST",
                url: "@Url.Action("LoadDataCity", "Admin")",
                data: '{}',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: OnSuccess,
                failure: function (response) {
                    alert(response);
                },
                error: function (response) {
                    alert(response);
                }
            });
        });

        function OnSuccess(response) {
            var users = eval(response);
            $("#city").DataTable(
                {
                    dom: 'rft<"tbl-f"pli>',
                    bLengthChange: true,
                    lengthMenu: [[5, 10, -1], [5, 10, "All"]],
                    bFilter: true,
                    bSort: true,
                    bPaginate: true,
                    language: {
                        info: " _START_ to _END_ of _TOTAL_ page(s)",
                        lengthMenu: " _MENU_ Items per page",
                        paginate: {
                            next: '&#8594;', // or '→'
                            previous: '&#8592;' // or '←' 
                        }
                    },
                    data: users,
                    columns: [
                        { "data": "ZoneName" },
                        { "data": "Name" },
                        {
                            "data": "Pincode",
                            "render": function (data) {
                                //data = data.split(',')
                                //    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
                                //    .join(', ')
                                return '<div class="pincode_wrp">' + data +'</div>';
                            }
                        },
                        {
                            "render": function (data, type, full, meta) { return '<a class="btn-edit" href="@Url.Action("CityCreate", "Admin")?id=' + full.Id + '"></a>'; }
                        },
                        {
                            data: null, render: function (data, type, row) {
                                return "<a href='#' class='btn-delete' onclick=DeleteData('" + row.Id + "'); ></a>";
                            }
                        },]
                });
        };


        function DeleteData(ID) {
            if (confirm("Are you sure you want to delete ...?")) {
                Delete(ID);
            }
            else {
                return false;
            }
        }


        function Delete(Id) {
            $.ajax({
                type: 'POST',
                url: baseUrl + 'Admin/DeleteCity',
                data: { "Id": Id },
                async: false,
                cache: false,
                success: function (response) {
                    if (response.result == "success") {
                        window.location.reload();
                    } else if (response.result == "failure") {
                        alert('Error deleting User');
                    }
                },
                complete: function () {

                },
                error: function () {
                }
            });

        }
    </script>
}

Skoda.DIAS.UI/Views/Admin/DocumentIndex.cshtml
@model List<AdminFileUpload>
@{
    ViewData["Title"] = "ŠKODA India > Document Upload";
    Layout = "_Layout";
} 
@section Styles {
    <link href="~/vendor/dataTables/jquery.dataTables.css" rel="stylesheet" />
    <link href=" https://cdn.datatables.net/buttons/2.1.0/css/buttons.dataTables.min.css" rel="stylesheet" />

}
@{ await Html.RenderPartialAsync("_LeftMenu", "ManageDocs"); }
<div class="dashboard">
    <div class="dashboard-inner">
        <a class="btn btn-primary mb-3" asp-action="UploadDocument">Upload Master Document</a>
        <table id="document" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>
                        File Name
                    </th>
                    <th>
                        File Path
                    </th>
                    <th>
                        Created Date
                    </th> 
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @if (@Model != null)
                {
                    @foreach (var m in @Model)
                    {
                        <tr>
                            <td>@m.FileName</td>
                            <td>@m.FilePath</td>
                            <td>@m.CreatedDate</td>
                            <td><a class="btn-edit" href="@Url.Action("UploadDocument", "Admin")?id= @m.Id"></a></td>
                            <td><a href='#' class='btn-delete' onclick="DeleteData(@m.Id); return false;"></a></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>
@section Scripts
{

    <script src="~/vendor/dataTables/jquery.dataTables.min.js"></script>

    <script type="text/javascript">

        $(function () {

            $.ajax({
                type: "POST",
                url: "@Url.Action("LoadDocument", "Admin")",
                data: '{}',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: OnSuccess,
                failure: function (response) {
                    alert(response);
                },
                error: function (response) {
                    alert(response);
                }
            });
        });

        function OnSuccess(response) {
            var users = eval(response);
            $("#document").DataTable(
                {
                    bLengthChange: true,
                    lengthMenu: [[5, 10, -1], [5, 10, "All"]],
                    bFilter: true,
                    bSort: true,
                    bPaginate: true,
                    dom: 'rft<"tbl-f"pli>',
                    language: {
                        info: " _START_ to _END_ of _TOTAL_ page(s)",
                        lengthMenu: " _MENU_ Items per page",
                        paginate: {
                            next: '&#8594;', // or '→'
                            previous: '&#8592;' // or '←' 
                        }
                    },
                    data: users,
                    columns: [
                        { "data": "FileName" },
                        { "data": "FilePath" },
                        { "data": "CreatedDate" }, 
                    {
                        data: null, render: function (data, type, row) {
                            return "<a href='#' class='btn-delete' onclick=DeleteData('" + row.Id + "'); ></a>";
                        }
                    },]
                });
        };


        function DeleteData(ID) {
            if (confirm("Are you sure you want to delete ...?")) {
                Delete(ID);
            }
            else {
                return false;
            }
        } 
        function Delete(ID) {
            $.ajax({
                type: 'POST',
                url: baseUrl + 'Admin/DeleteDocument',
                data: { "Id": ID },
                async: false,
                cache: false,
                success: function (response) {
                    if (response.result == "success") {
                        window.location.reload();
                    } else if (response.result == "failure") {
                        alert('Error deleting doc');
                    }
                },
                complete: function () {

                },
                error: function () {
                }
            });

        }
    </script>
}

Skoda.DIAS.UI/Views/Admin/Enquirystatus.cshtml
@model EnquiryStatusUpdate
@using Skoda.DIAS.Common.Enums;
@{
    ViewData["Title"] = "ŠKODA India > Status Update";
}
<div class="dashboard">
    <div class="dashboard-inner user_create">
        <h1 class="page-title mb-4">Enquiry Status Update</h1>

        <form asp-action="Enquirystatus" method="post">
            <div class="row">
                <div class="col-sm-6">
                    <label class="custom-field two">
                        <input asp-for="Comment" class="form__field" autocomplete="off" placeholder="&nbsp;" />
                        <span class="placehold">Comment</span>
                        <input hidden asp-for="Status" />
                        <input hidden asp-for="Updated" />
                        <input hidden asp-for="Id" />
                    </label>
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-7">
                    <input type="submit" value="Save" id="btnsubmit" class="btn btn-primary pl-4 pr-4" />
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function () { 
    if ('@Model.Updated' == '1')
    {
    alert("Enquiry Status already rejected");
    $("#btnsubmit").attr('disabled', true);}
    });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

Skoda.DIAS.UI/Views/Admin/ForgotPasswordConfirmation.cshtml
@{
    ViewData["Title"] = "ŠKODA India";
    Layout = "_LoginLayout";
}
<div class="login-wrapper">
    <div class="left-div">
        <div class="img-wrapper-logi">
            <img class="img-fluid"
                 src="~/images/login/login-banner.svg"
                 alt="login-banner" />
            <div class="login-page-title">
                <h1>Project Change Management</h1>
                <p>Your one stop tool for all your project & team management</p>
            </div>
        </div>
    </div>
    <div class="right-div">
        <div class="form-wrapper">
            <div class="login-logo">
                <img class="img-fluid" src="~/images/common/logo.svg" alt="logo" />


            </div>
            <div class="login-info">
                <h3>Forgot Pasword Confirmation</h3>
                <p>
                    he link has been sent, please check your email to login system.
                </p>
            </div>
             
        </div>
    </div>
</div>

Skoda.DIAS.UI/Views/Admin/Forgotpassword.cshtml
@model ForgotPassModel
@{
    ViewData["Title"] = "ŠKODA India";
    Layout = "_LoginLayout";
}

<div class="container">
    <div class="login-wrapper">
        <div class="left-div">
            <img src="~/images/login/admin-login-bg-large.png" class="img-fluid" />
        </div>
        <div class="right-div">
            <div class="form-wrapper">
                <div class="login-info">
                    <h3>ŠKODA Dealer Enquiry Management Portal</h3>
                    <h5>Forgot Pasword</h5>
                    <p hidden>
                        Collaboratively administrate empowered markets via plug-and-play
                        networks. Dynamically procrastinate B2C users after.
                    </p>
                </div>
                <form asp-action="Forgotpassword" asp-controller="Admin">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form__group field">
                        <input asp-for="Username" class="form__field" autocomplete="off" placeholder="User ID" />
                        <label for="Username" class="form__label">Email Addresss</label>
                        <span asp-validation-for="Username" class="text-danger"></span>
                    </div>
                    <div class="form-inline justify-content-end mt-4">
                        <a style="color:#000;text-decoration:underline"  asp-action="Index" asp-controller="Admin"><small> Back to Login? </small></a>
                        <button type="submit" class="btn btn-primary ml-4">
                            Send Email
                        </button>
                    </div>
                    <span id="errormessage">
                        @if (Model.ErrorMessage != null)
                        {
                            <label class="field-validation-valid text-danger">@Model.ErrorMessage.ToString()</label>;
                        }
                    </span>
                </form>                
            </div>
        </div>
    </div>
</div>

Skoda.DIAS.UI/Views/Admin/Index.cshtml
@model List<UserDetails>
@{
    ViewData["Title"] = "ŠKODA India > Users";
    Layout = "_Layout";
}

@section Styles {
    <link href="~/vendor/dataTables/jquery.dataTables.css" rel="stylesheet" />
    <link href=" https://cdn.datatables.net/buttons/2.1.0/css/buttons.dataTables.min.css" rel="stylesheet" />

}
@{ await Html.RenderPartialAsync("_LeftMenu", "ManageUsers"); }
<div class="dashboard">
    <div class="dashboard-inner">
        <a class="btn btn-primary mb-3" asp-action="Create">Create New</a>
        <table id="user" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>
                        Fullname
                    </th>
                    <th>
                        UserID
                    </th>
                    <th>
                        Mobile
                    </th>
                    <th>
                        City
                    </th>
                    <th>
                        Role
                    </th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @if (@Model != null)
                {
                    @foreach (var m in @Model)
                    {
                        <tr>
                            <td>@m.Fullname</td>
                            <td>@m.Username</td>
                            <td>@m.Mobile</td>
                            <td>@m.City</td>
                            <td>@m.Role</td>
                            <td><a class="btn-edit" href="@Url.Action("Create", "Admin")?id= @m.UserId"></a></td>
                            <td><a href='#' class='btn-delete' onclick="DeleteData(@m.UserId); return false;"></a></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>
@section Scripts
{

    <script src="~/vendor/dataTables/jquery.dataTables.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/2.1.0/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.1.0/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.1.0/js/buttons.print.min.js"></script>

    <script type="text/javascript">

        $(function () {

            $.ajax({
                type: "POST",
                url: "@Url.Action("LoadData", "Admin")",
                data: '{}',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: OnSuccess,
                failure: function (response) {
                    alert(response);
                },
                error: function (response) {
                    alert(response);
                }
            });
        });

        function OnSuccess(response) {
            var users = eval(response);
            $("#user").DataTable(
                {
                    dom: 'Bfrt<"tbl-f"pli>',
                    buttons: [
                        'excel'
                    ],
                    bLengthChange: true,
                    lengthMenu: [[5, 10, -1], [5, 10, "All"]],
                    bFilter: true,
                    bSort: true,
                    bPaginate: true,
                    
                    language: {
                        info: " _START_ to _END_ of _TOTAL_ page(s)",
                        lengthMenu: " _MENU_ Items per page",
                        paginate: {
                            next: '&#8594;', // or '→'
                            previous: '&#8592;' // or '←' 
                        }
                    },
                    data: users,
                    columns: [
                        { "data": "Fullname" },
                        { "data": "UserId" },
                        { "data": "Mobile" },
                        { "data": "City" },
                        { "data": "Role" },
                        {
                            "render": function (data, type, full, meta) { return '<a class="btn-edit" href="@Url.Action("Create", "Admin")?id=' + full.UserId + '"></a>'; }
                        },
                    {
                        data: null, render: function (data, type, row) {
                            return "<a href='#' class='btn-delete' onclick=DeleteData('" + row.UserId + "'); ></a>";
                        }
                    },]
                });
        };


        function DeleteData(CustomerID) {
            if (confirm("Are you sure you want to delete ...?")) {
                Delete(CustomerID);
            }
            else {
                return false;
            }
        }


        function Delete(UserID) {
            $.ajax({
                type: 'POST',
                url: baseUrl + 'Admin/Delete',
                data: { "Id": UserID },
                async: false,
                cache: false,
                success: function (response) {
                    if (response.result == "success") {
                        window.location.reload();
                    } else if (response.result == "failure") {
                        alert('Error deleting User');
                    }
                },
                complete: function () {

                },
                error: function () {
                }
            });

        }
    </script>
}

Skoda.DIAS.UI/Views/Admin/Profile.cshtml
@model UserProfile
@using Skoda.DIAS.Common.Enums;
@{
    ViewData["Title"] = "ŠKODA India > Profile";
}@{ await Html.RenderPartialAsync("_LeftMenu", "Admin"); }

<div class="dashboard">
    <div class="dash-content">
        <div class="dashboard-inner  user_create">
            <h1 class="page-title mb-4">User Profile</h1>

            <form asp-action="Profile" asp-controller="Admin">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row">
                    <div class="col-sm-6">
                        <label class="custom-field two">
                            <input asp-for="FullName" class="form__field" autocomplete="off" placeholder="&nbsp;" />
                            <span class="placehold">Full Name</span>
                            <input hidden asp-for="UserId" />
                            <span asp-validation-for="FullName" class="error-message" aria-live="polite"></span>
                        </label>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <label class="custom-field two">

                            <input asp-for="Username" class="form__field" autocomplete="off" placeholder="&nbsp;" />
                            <span class="placehold">Email ID</span>
                            <input hidden asp-for="UserId" />
                            <span asp-validation-for="Username" class="error-message" aria-live="polite"></span>
                        </label>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <label class="custom-field two">
                            <label class="control-label">Choose Role</label>
                            <select asp-for="RoleId" class="form-control custom-select" asp-items="Model.Roles">
                            </select>
                            <span class="error-message" aria-live="polite"></span>
                        </label>
                    </div>

                </div>

                <div class="form-row">
                    <hr />
                </div>
                <div class="form-row">
                    <div class="col mr-3">
                        <a asp-controller="ChangePassword" asp-action="Index" class="btn btn-primary mr-2" asp-route-id="@Model.UserId">Change Password</a>
                        <input type="submit" value="Update" class="btn btn-primary" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>

    </script>

}

Skoda.DIAS.UI/Views/Admin/RoleCreate.cshtml
@model RoleDetails
@using Skoda.DIAS.Common.Enums;
@{
    ViewData["Title"] = "ŠKODA India > Create Role";
}
@{ await Html.RenderPartialAsync("_LeftMenu", "ManagerUsers"); }
<div class="dashboard">
    <div class="dashboard-inner user_create">
        <h1 class="page-title mb-4">Create Role</h1>
        <form asp-action="RoleCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (!string.IsNullOrEmpty(Model.ErrorMessage))
            {
                <div class="text-danger">@Model.ErrorMessage</div>
            }

            <div class="form-group row">
                <div class="col-sm-6">
                    <label class="custom-field two">

                        <input asp-for="Name" class="form__field" autocomplete="off" placeholder="&nbsp;" />
                        <span class="placehold">Role</span>
                        <input asp-for="RoleId" hidden />
                        <span asp-validation-for="Name" class="error-message" aria-live="polite"></span>
                    </label>
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-7">
                    <input type="submit" value="Save" class="btn btn-primary pl-4 pr-4" />

                    <a asp-action="RoleList" class="cancel-btn pl-4 pr-4">Cancel</a>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

Skoda.DIAS.UI/Views/Admin/StateCreate.cshtml
@model StateDetails
@using Skoda.DIAS.Common.Enums;
@{
    ViewData["Title"] = "ŠKODA India > Create State";
}
@{ await Html.RenderPartialAsync("_LeftMenu", "ManagerUsers"); }
<div class="dashboard">
    <div class="dashboard-inner user_create">
        <h1 class="page-title mb-4">Create State</h1>
        <form asp-action="StateCreate" method="post">
            @if (!string.IsNullOrEmpty(Model.ErrorMessage))
            {
                <div class="text-danger">@Model.ErrorMessage</div>
            }
            <div class="row">
                <div class="col-sm-6">
                    <label class="custom-field two">
                        <input hidden asp-for="Id" />
                        <label class="control-label">Choose Zone</label>
                        <select asp-for="ZoneId" class="form-control custom-select" asp-items="Model.Zones">
                        </select>
                        <span asp-validation-for="ZoneId" class="error-message" aria-live="polite"></span>
                    </label>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <label class="custom-field two">                        
                        <input asp-for="Name" class="form__field" autocomplete="off" placeholder="&nbsp;" />
                        <span class="placehold">State</span>
                        <span asp-validation-for="Name" class="error-message" aria-live="polite"></span>
                    </label>                    
                </div>
            </div> 
            <div class="form-row">
                <div class="col-lg-7">
                    <input type="submit" value="Save" class="btn btn-primary pl-4 pr-4" />
                    <a asp-action="StateList" class="cancel-btn pl-4 pr-4">Cancel</a>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");} 

}